version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_prod
    restart: always

    environment:
      POSTGRES_DB: postos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: deltasollutions

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
